### ISSUE TITLE
dcload-serial (target) does not return to main screen

### ISSUE THREAD

**Issue by Tchan0** [KallistiOS/dcload-serial#22]
When launching eg 2ndmix.elf, and pressing the start button to exit, 
dcload-ser target does not return to the main screen, requiring a hard reboot of the Dreamcast.

This problem does not appear with dcload-ip

**Comment by ljsebald** [comment]
Testing revealed that this is not something that actually is an issue -- dcload-serial still works, it just leaves the screen with whatever was on it until something causes dcload to refresh the screen. No reboot is needed.
